monitor.bluez.properties = {
    ## Force high-quality Bluetooth codecs in order of absolute best preference
    bluez5.codecs = [ ldac aptx_hd aptx aac sbc_xq sbc ]

    ## Stop your headphones from reverting to low-quality mono headset mode (mics)
    bluez5.roles = [ a2dp_sink a2dp_source ]
}

wireplumber.settings = {
    ## Disables the annoying auto-switch to horrible-sounding mono handsfree (HFP) mode
    bluetooth.autoswitch-to-headset-profile = false
}
