# ==========================================
# TOKYODARK THEME (tiagovla/tokyodark.nvim)
# ==========================================
background            #11121D
foreground            #A0A8E3
selection_background  #212234
selection_foreground  #A0A8E3
url_color             #95D3AF
cursor                #A0A8E3
cursor_text_color     #11121D

# Window borders
active_border_color   #7199EE
inactive_border_color #212234
bell_border_color     #D7A65F

# Tab bar
active_tab_background   #7199EE
active_tab_foreground   #11121D
inactive_tab_background #212234
inactive_tab_foreground #A0A8E3
tab_bar_background      #0a0b14

# The 16 Terminal Colors
# Black
color0 #0a0b14
color8 #212234
# Red
color1 #EE6D85
color9 #EE6D85
# Green
color2  #95D3AF
color10 #95D3AF
# Yellow
color3  #D7A65F
color11 #D7A65F
# Blue
color4  #7199EE
color12 #7199EE
# Purple / Magenta
color5  #A485DD
color13 #A485DD
# Cyan
color6  #77A8D6
color14 #77A8D6
# White
color7  #A0A8E3
color15 #c0caf5
