# vim:ft=kitty

## name: TokyoDark
## Based on: tiagovla/tokyodark.nvim

############################
# General
############################

background              #11121d
foreground              #a0b3c5

selection_background    #2c3549
selection_foreground    #ffffff

url_color               #4fd6be

cursor                  #a0b3c5
cursor_text_color       #11121d

############################
# Tabs
############################

active_tab_background   #7199ee
active_tab_foreground   #11121d

inactive_tab_background #1b1d2b
inactive_tab_foreground #5a6883

tab_bar_background      #11121d

############################
# Windows
############################

active_border_color     #7199ee
inactive_border_color   #1b1d2b

############################
# Normal Colors
############################

color0  #11121d
color1  #ee6d85
color2  #95c561
color3  #d7a65f
color4  #7199ee
color5  #a485dd
color6  #38a89d
color7  #a0b3c5

############################
# Bright Colors
############################

color8  #4a5057
color9  #ff7a93
color10 #a7d66d
color11 #ebb86c
color12 #82aaff
color13 #bb9af7
color14 #5fd7c7
color15 #d6deeb

############################
# Extended
############################

color16 #f6955b
color17 #db4b4b
