-- #######################################################################################
-- AUTOGENERATED HYPRLAND LUA CONFIG - TOKYO DARK EDITION
-- #######################################################################################

require("windowrules")
require("keybinds")

------------------
---- MONITORS ----
------------------

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1",
})

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl enable --now auto-cpufreq")
	hl.exec_cmd("nm-applet &")
	hl.exec_cmd("~/.config/hypr/scripts/waybar.sh")
	hl.exec_cmd("vicinae server")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("swaync")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("~/.config/hypr/scripts/battery/battery-watch.sh")
end)

hl.exec_cmd("hyprshade on vibrance")

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	general = {
		gaps_in = 7,
		gaps_out = 7,

		border_size = 2,

		col = {
			-- Smooth gradient from Tokyo Blue to Tokyo Green
			active_border = { colors = { "rgba(7199eeee)", "rgba(9ece6aee)" }, angle = 45 },
			-- Deep Tokyo Dark Gray for inactive windows
			inactive_border = "rgba(212234ee)",
		},

		resize_on_border = true,
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {
		rounding = 7,
		rounding_power = 2,

		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = true,
			range = 20, -- Expanded range for a softer, deeper shadow
			render_power = 3,
			color = 0x88000000, -- Smooth, dark drop shadow (equivalent to rgba(00000088))
		},

		blur = {
			enabled = true,
			size = 4, -- Boosted for better background isolation
			passes = 3, -- 3 passes creates a smooth, premium glass effect
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},

	dwindle = {
		preserve_split = true,
	},

	master = {
		new_status = "master",
	},

	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
		vrr = 1,
		on_focus_under_fullscreen = 1,
		disable_xdg_env_checks = true,
		disable_watchdog_warning = true,
	},

	debug = {
		vfr = true,
	},

	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,
		sensitivity = 0,

		touchpad = {
			natural_scroll = true,
			drag_3fg = 1,
		},
	},
})

--------------------
---- ANIMATIONS ----
--------------------

-- Physics-based and Material Design Bezier curves
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.36, 0 }, { 0.66, -0.56 } } })
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })

-- Application of animations
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })

-- Windows: Snappy pop-in with a micro-bounce, smooth shrinking pop-out
hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "overshot" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "overshot", style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "smoothOut", style = "popin 80%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "md3_decel" })

-- Borders: Smoothly rotating gradient on active windows
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 100, bezier = "linear", style = "loop" })

-- Fades: Soft and seamless
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "smoothIn" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 5, bezier = "md3_decel" })

-- Workspaces: Fast, fluid sliding with a slight fade
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "md3_decel", style = "slidefade 20%" })

-- Layers (Waybar, SwayNC, OSD): Quick and responsive fades
hl.animation({ leaf = "layers", enabled = true, speed = 4, bezier = "md3_decel", style = "fade" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "md3_decel", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 3, bezier = "smoothOut", style = "fade" })

------------------------------
---- GESTURES AND DEVICES ----
------------------------------

hl.gesture({
	fingers = 4,
	direction = "horizontal",
	action = "workspace",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})
