$font = JetBrains Mono Nerd Font

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = easeOut, 0.33, 1, 0.68, 1
    animation = fadeIn, 1, 4, easeOut
    animation = fadeOut, 1, 4, easeOut
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/bhupeshr45/Pictures/Wallpapers/Anime/onepiece4.png
    blur_passes = 3
    blur_size = 4
    
    # Dimmed slightly to give the lockscreen a true "dark glass" feel
    contrast = 0.95
    brightness = 0.65
    vibrancy = 0.15
}

# ------------------------------
# INPUT FIELD STYLING
# ------------------------------
input-field {
    monitor =
    size = 22%, 6%
    outline_thickness = 2
    rounding = 16

    # Tokyo Dark Gray translucent pocket
    inner_color = rgba(33, 34, 52, 0.75) 

    # Muted border transitioning to Tokyo Blue on typing, Tokyo Red on fail
    outer_color = rgba(74, 80, 87, 1.0)
    check_color = rgba(113, 153, 238, 1.0)
    fail_color = rgba(238, 109, 133, 1.0)

    # Lavender White typed text
    font_color = rgb(192, 202, 245) 
    fade_on_empty = false

    dots_spacing = 0.35

    # Pango markup used here to color the placeholder text Tokyo Lavender
    placeholder_text = <span foreground="##A0A8E3">  Enter Password...</span>
    fail_text = <span foreground="##11121D"> Authentication Failed</span>

    font_family = $font

    position = 0, -120
    halign = center
    valign = center
}

# ------------------------------
# TIME
# ------------------------------
label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p"
    font_size = 140
    font_family = $font
    
    # Crisp Lavender White
    color = rgb(192, 202, 245)

    shadow_passes = 2
    shadow_size = 12
    shadow_color = rgba(0,0,0,0.45)

    position = 0, 130
    halign = center
    valign = center
}

# ------------------------------
# DATE
# ------------------------------
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 34
    font_family = $font
    
    # Tokyo Blue highlight for the date
    color = rgb(113, 153, 238)

    shadow_passes = 2
    shadow_size = 10
    shadow_color = rgba(0,0,0,0.45)

    # position = 0, 30
    halign = center
    valign = center
}

# ------------------------------
# KEYBOARD LAYOUT
# ------------------------------
# label {
#     monitor =
#     text =   $LAYOUT[en,ru]
#     font_size = 26
#     onclick = hyprctl switchxkblayout all next
#
#     font_family = $font
#     color = rgb(160, 168, 227) # Muted Lavender
#     padding = 6, 12
#     rounding = 6
#
#     shadow_passes = 1
#     shadow_size = 5
#     shadow_color = rgba(0,0,0,0.4)
#
#     position = 0, -260
#     halign = center
#     valign = center
# }
